### ISSUE TITLE
Combining with a search form?

### ISSUE THREAD

**Issue by louisjansen** [webz2feel/google-custom-search-api#1]
Hi there, great to have this already!

But how can I connect this class to a simple form in html to create my own Google Custom Search API function on my website with this? Could this be included? Or any tips/hints?

Kind regards,

Louis

**Comment by grim-reapper** [comment]
You have to create a simple search form that will take user input, then you grab the user input in your form processing file and pass the input to custom search class... that's it.

**Comment by louisjansen** [comment]
> You have to create a simple search form that will take user input, then you grab the user input in your form processing file and pass the input to custom search class... that's it.

Where you solution seem to be the 'end part'. The input part I managed to setup with this video. [https://www.youtube.com/watch?v=c3qWHnJJbSY](url).

However, simply replacing the login.php with CustomSearch.php does no do the job (which I do understand). Any clue on what why I have to refer to the php class or file from the form?

**Comment by grim-reapper** [comment]
> > You have to create a simple search form that will take user input, then you grab the user input in your form processing file and pass the input to custom search class... that's it.
> 
> Where you solution seem to be the 'end part'. The input part I managed to setup with this video. [https://www.youtube.com/watch?v=c3qWHnJJbSY](url).
> 
> However, simply replacing the login.php with CustomSearch.php does no do the job (which I do understand). Any clue on what why I have to refer to the php class or file from the form?

The process will be same like you are doing in the video for fetch API.  There would a form like you have with search field.. you have to process the request same way you are doing in the video then in login.php or whatever you named that file will require customSearch.php class which will send api request to google and give you result back in json format. You can manuplate data according to your requirement. still got any confusion write me back.

**Comment by louisjansen** [comment]
Ok, this is my code 

`<html><head><title>Search Results</title></head><body><h1>Zoeken</h1><form method="GET" id="searchForm"> 
    <label for="q">Search:</label>
    <input type="text" name="q" id="q" size="30" value="" placeholder="What are you searching for..." autocomplete="off">
    <button type="submit">Search</button>    
</form>
<script>
    const searchForm = document.getElementById('searchForm');

    searchForm.addEventListener('submit', function (e) {
        e.preventDefault();

        const formData = new FormData(this);

        const searchParams = new URLSearchParams();

        for (const pair of formData) {        
            searchParams.append(pair[0], pair[1]);
        }

        fetch('login.php', {    
            method: 'post',
            body: searchParams
        }).then(function (response) {
            return response.text();
        }).then(function (text) {
            console.log(text);
        }).catch(function (error) {
            console.error(error);
        })
    });
</script>

</body>
</html>`


and the code of login.php is like this:

`<?php

use Fogg\Google\CustomSearch\CustomSearch;
require 'CustomSearch.php';

//Initialize the search class
$cs = new CustomSearch();

//Perform a simple search
$response = $cs->simpleSearch('whole foods');

//Perform a search with extra parameters
$response2 = $cs->search('whole foods', ['excludeTerms'=>'tomato']);


?>`

What is not in place than?

**Comment by grim-reapper** [comment]
> Ok, this is my code
> 
> `<title>Search Results</title>
> 
> # Zoeken
> 
> Search:
> 
> Search
> <script> const searchForm = document.getElementById('searchForm');
> ```
> searchForm.addEventListener('submit', function (e) {
>     e.preventDefault();
> 
>     const formData = new FormData(this);
> 
>     const searchParams = new URLSearchParams();
> 
>     for (const pair of formData) {        
>         searchParams.append(pair[0], pair[1]);
>     }
> 
>     fetch('login.php', {    
>         method: 'post',
>         body: searchParams
>     }).then(function (response) {
>         return response.text();
>     }).then(function (text) {
>         console.log(text);
>     }).catch(function (error) {
>         console.error(error);
>     })
> });
> ```
> 
> </script> `
> and the code of login.php is like this:
> 
> `<?php
> 
> use Fogg\Google\CustomSearch\CustomSearch;
> require 'CustomSearch.php';
> 
> //Initialize the search class
> $cs = new CustomSearch();
> 
> //Perform a simple search
> $response = $cs->simpleSearch('whole foods');
> 
> //Perform a search with extra parameters
> $response2 = $cs->search('whole foods', ['excludeTerms'=>'tomato']);
> 
> ?>`
> 
> What is not in place than?

Everything seems okay in your code, so what issue are you having right now?

**Comment by grim-reapper** [comment]
> > Ok, this is my code
> > `<title>Search Results</title>
> > # Zoeken
> > Search:
> > Search
> > <script> const searchForm = document.getElementById('searchForm');
> > ```
> > searchForm.addEventListener('submit', function (e) {
> >     e.preventDefault();
> > 
> >     const formData = new FormData(this);
> > 
> >     const searchParams = new URLSearchParams();
> > 
> >     for (const pair of formData) {        
> >         searchParams.append(pair[0], pair[1]);
> >     }
> > 
> >     fetch('login.php', {    
> >         method: 'post',
> >         body: searchParams
> >     }).then(function (response) {
> >         return response.text();
> >     }).then(function (text) {
> >         console.log(text);
> >     }).catch(function (error) {
> >         console.error(error);
> >     })
> > });
> > ```
> > 
> > </script> `
> > and the code of login.php is like this:
> > `<?php
> > use Fogg\Google\CustomSearch\CustomSearch;
> > require 'CustomSearch.php';
> > //Initialize the search class
> > $cs = new CustomSearch();
> > //Perform a simple search
> > $response = $cs->simpleSearch('whole foods');
> > //Perform a search with extra parameters
> > $response2 = $cs->search('whole foods', ['excludeTerms'=>'tomato']);
> > ?>`
> > What is not in place than?
> 
> Everything seems okay in your code, so what issue are you having right now?

You have to replace "whole foods" with search keywords that you will get from post form.

**Comment by louisjansen** [comment]
But that would be a variable since the input will differ for each user right? The thing is, if I try to load login.php I only see a blank screen. No matter what keywords are in there.

**Comment by grim-reapper** [comment]
> But that would be a variable since the input will differ for each user right? The thing is, if I try to load login.php I only see a blank screen. No matter what keywords are in there.

How input can be different? suppose you have search box <input type="text" name="search" /> the name of field will always be same. this is the name that you will get in login.php file and pass it's value to customsearch function...!! isn't ?

**Comment by louisjansen** [comment]
Sorry for misunderstanding you. With this comment "You have to replace "whole foods" with search keywords that you will get from post form" you did seem to refer to the keywords the user is using. Apparently I have to refer to the name of the input field that is capturing the query. In my form that name is "q".

But even if I replace "whole foods" with "q", nothing happens
